import { getPayload } from 'payload'
import config from '../../payload.config'

const migrate = async () => {
  const payload = await getPayload({ config })

  console.log('--- Phase 1: Migrating Categories ---')
  const categories = await payload.find({
    collection: 'categories',
    limit: 1000,
  })

  console.log(`Found ${categories.docs.length} categories to process...`)

  for (const doc of categories.docs) {
    if (doc.slug && !doc.adminLabel) {
      console.log(`Migrating Category: ${doc.slug} -> adminLabel`)
      // @ts-ignore
      await payload.update({
        collection: 'categories',
        id: doc.id,
        data: {
          adminLabel: doc.slug,
          // slug will be automatically regenerated by the beforeValidate hook
        },
      })
    }
  }

  console.log('--- Phase 2: Migrating FAQ Items ---')
  const faqs = await payload.find({
    collection: 'faq-items',
    limit: 1000,
  })

  console.log(`Found ${faqs.docs.length} FAQ items to process...`)

  for (const doc of faqs.docs) {
    // Only migrate if adminLabel is empty and slug exists
    if (doc.slug && !doc.adminLabel) {
      console.log(`Migrating FAQ Item: ${doc.slug} -> adminLabel`)
      // @ts-ignore
      await payload.update({
        collection: 'faq-items',
        id: doc.id,
        data: {
          adminLabel: doc.slug,
          // slug will be automatically regenerated by the beforeValidate hook
        },
      })
    }
  }

  console.log('--- Migration Completed Successfully ---')
  process.exit(0)
}

migrate().catch(console.error)
