"use client";

import { useState, useEffect, useRef } from "react";
import { motion, useScroll, useTransform } from "framer-motion";
import type { Locale } from "@/i18n.config";
import { LexicalRenderer } from "@/components/lexical/LexicalRenderer";
import Link from "next/link";
import {
  EyoloCornerRound,
  EyoloScrollBadge,
} from "@/components/blog/ReplicaAssets";

interface BlogTemplateProps {
  blog: any;
  locale: Locale;
  formatDate: (date: string) => string;
}

export function BlogTemplateOne({
  blog,
  locale,
  formatDate,
}: BlogTemplateProps) {
  const [activeSection, setActiveSection] = useState<string>("");
  const containerRef = useRef<HTMLDivElement>(null);
  const sidebarRef = useRef<HTMLDivElement>(null);
  
  const { scrollY } = useScroll();
  const [sidebarLimit, setSidebarLimit] = useState(0);
  const [offsetTop, setOffsetTop] = useState(0);
  
  useEffect(() => {
    if (containerRef.current && sidebarRef.current) {
      // 获取正文容器距离页面顶部的距离
      setOffsetTop(containerRef.current.offsetTop);
      // 获取可滑动的最大范围
      setSidebarLimit(containerRef.current.offsetHeight - sidebarRef.current.offsetHeight);
    }
  }, [blog]);

  // 精准磁吸：在特定滚动区间内，实现 1:1 的位移补偿
  // 减去 96px 是为了预留 top-24 的间距，与原 Layout 保持一致
  const sidebarY = useTransform(
    scrollY, 
    [offsetTop - 96, offsetTop - 96 + sidebarLimit], 
    [0, sidebarLimit],
    { clamp: true }
  );

  // Mapping to IDs generated by LexicalRenderer (slugified text content)
  const mockToc = [
    {
      id: "understanding-self-care",
      title: locale === "zh" ? "理解自我保健" : "Understanding Self-Care",
    },
    {
      id: "importance-of-self-care",
      title: locale === "zh" ? "自我保健的重要性" : "Importance of Self-Care",
    },
    {
      id: "practical-strategies-for-self-care",
      title: locale === "zh" ? "实用策略" : "Practical Strategies",
    },
    { id: "conclusion", title: locale === "zh" ? "结论" : "Conclusion" },
  ];

  // Intersection Observer for Scroll Spy
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        // Track the element that is most prominent in the top 30% of the screen
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        });
      },
      { rootMargin: "-20% 0px -70% 0px" },
    );

    mockToc.forEach((item) => {
      const el = document.getElementById(item.id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, [blog]); // Re-run if blog content changes

  const suggestedPosts = [
    {
      id: "sp1",
      category: "creativity",
      title:
        "Unleashing Creativity: Exploring Creative Practices to Spark Innovation",
      date: "Dec 15, 2023",
      author: "Nilima Nike",
      readTime: "02 MIN TO READ",
      image:
        "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=400&fit=crop",
    },
    {
      id: "sp2",
      category: "happiness",
      title:
        "The Science of Happiness: Cultivating Joy and Fulfillment in Everyday Life",
      date: "May 28, 2024",
      author: "Alex Walton",
      readTime: "03 MIN TO READ",
      image:
        "https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=600&h=400&fit=crop",
    },
    {
      id: "sp3",
      category: "startups",
      title: "First Look: Nine New Indie Bio Companies That Present to VCs",
      date: "May 12, 2024",
      author: "Nilima Nike",
      readTime: "03 MIN TO READ",
      image:
        "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&h=400&fit=crop",
    },
  ];

  return (
    <article
      className="min-h-screen bg-white font-lexend-deca antialiased selection:bg-[#ff4848] selection:text-white"
      data-header-theme="light"
    >
      {/* 1. Post Header Info */}
      <div id="post-header" className="py-16 sm:py-20 overflow-clip">
        <div className="container mx-auto px-6">
          <div className="flex flex-col lg:flex-row lg:flex-nowrap items-center">
            <div className="lg:w-6/12 text-center lg:text-left">
              <div className="mb-6 flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-x-4 gap-y-1">
                <Link
                  href={`/${locale}/blog`}
                  className="uppercase bg-white/10 border border-[#DCDBD0] rounded-md px-4 py-2 text-[10px] font-bold tracking-widest block text-[#ff4848] hover:text-white hover:bg-[#ff4848] transition-all duration-300 w-fit lg:mx-0"
                >
                  {blog.categories?.[0]?.name || "self-care"}
                </Link>
                <span className="font-extralight opacity-40">—</span>
                <p className="text-gray-500 text-xs font-medium">
                  {formatDate(blog.publishedAt)}
                </p>
              </div>

              {/* User Req: H1 Title 29px */}
              <h1 className="text-[29px] font-prata !leading-[1.4] mb-10 text-[#060C14]">
                {blog.title}
              </h1>

              <ul className="flex flex-wrap items-center justify-center lg:justify-start gap-3 gap-y-1 uppercase text-[10px] font-bold tracking-[0.2em] text-[#060C14] mb-12">
                <li className="flex items-center gap-2">
                  <span className="text-gray-400 font-medium lowercase italic opacity-80">
                    Author of the post -
                  </span>
                  <Link
                    href="#"
                    className="hover:text-[#ff4848] transition-all duration-300 underline underline-offset-4"
                  >
                    {blog.author || "Kathryn Jackson"}
                  </Link>
                </li>
                <li className="text-gray-300 opacity-40">•</li>
                <li>03 MIN TO READ</li>
              </ul>

              <div className="flex items-center justify-center lg:justify-start gap-4 text-[10px] font-bold uppercase tracking-[0.4em] text-gray-400">
                <span>— scroll down</span>
                <span className="opacity-40">—</span>
                <span>read more</span>
              </div>
            </div>

            <div className="lg:w-8/12 w-full mt-12 lg:mt-0 lg:pl-12">
              <div className="relative w-full aspect-[16/11]">
                <img
                  className="rounded-3xl object-cover bg-dark/10 w-full h-full shadow-2xl"
                  src={
                    blog.coverImage ||
                    "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=1200"
                  }
                  alt={blog.title}
                />
                <EyoloCornerRound className="absolute bottom-0 left-0 z-20 rotate-90 w-6 h-6 text-white" />
                <EyoloCornerRound className="absolute top-0 right-0 z-20 -rotate-90 w-6 h-6 text-white" />
                <div className="absolute -bottom-10 left-3 lg:-left-12">
                  <EyoloScrollBadge />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-6 hidden lg:block">
        <hr className="border-[#F0EBE6]" />
      </div>

      {/* 3. Main Content Grid */}
      <div className="lg:pt-20 pb-24">
        <div className="container mx-auto px-6">
          <div ref={containerRef} className="flex flex-col lg:flex-row gap-16 relative">
            {/* Main Content Column */}
            <div className="lg:w-8/12 xl:w-9/12">
              <div
                id="post-content"
                className="prose prose-lg max-w-none 
                prose-headings:font-prata prose-headings:text-[#060C14] prose-headings:!leading-tight
                prose-h2:text-[24px] prose-h2:mt-16 prose-h2:mb-8
                prose-p:text-[16px] prose-p:text-gray-600 prose-p:leading-[1.8] prose-p:mb-8
                prose-li:text-[16px] prose-li:text-gray-600 prose-li:mb-2
                prose-blockquote:border-0 prose-blockquote:p-0 prose-blockquote:my-16 
                prose-blockquote:text-[24px] prose-blockquote:italic prose-blockquote:text-[#060C14] prose-blockquote:text-center prose-blockquote:mx-auto prose-blockquote:max-w-3xl"
              >
                {/* 1:1 Hardcoded Article Content to bypass any rendering issues */}
                <div className="space-y-10">
                  <p className="text-[16px] leading-[1.8] text-gray-600">
                    In today's fast-paced and demanding world, prioritizing
                    self-care is essential for maintaining balance, managing
                    stress, and preserving your well-being. Despite the
                    pressures of work, family, and other responsibilities,
                    finding time for self-care is crucial for overall health and
                    happiness. In this post, we'll explore the importance of
                    self-care and share practical strategies for finding balance
                    in a busy world.
                  </p>

                  <section
                    id="understanding-self-care"
                    className="scroll-mt-32"
                  >
                    <h2 className="text-[24px] font-prata text-[#060C14] mb-6">
                      Understanding Self-Care
                    </h2>
                    <p className="text-[16px] leading-[1.8] text-gray-600">
                      Self-care involves taking intentional actions to nurture
                      your physical, mental, and emotional well-being. It
                      encompasses a wide range of activities, including
                      exercise, relaxation, hobbies, socializing, and seeking
                      support when needed. Self-care is not a one-size-fits-all
                      concept; it is a personalized practice that varies from
                      person to person based on their unique needs and
                      preferences.
                    </p>
                  </section>

                  <section
                    id="importance-of-self-care"
                    className="scroll-mt-32"
                  >
                    <h2 className="text-[24px] font-prata text-[#060C14] mb-6">
                      Importance of Self-Care
                    </h2>
                    <ul className="list-disc pl-6 space-y-4 text-[16px] leading-[1.8] text-gray-600">
                      <li>
                        <strong className="text-[#060C14]">
                          Stress Management:
                        </strong>{" "}
                        Self-care activities such as exercise, meditation, and
                        deep breathing can help reduce stress levels and promote
                        relaxation, which in turn improves your overall mental
                        and physical health.
                      </li>
                      <li>
                        <strong className="text-[#060C14]">
                          Enhanced Productivity:
                        </strong>{" "}
                        Taking time for self-care can improve focus,
                        concentration, and productivity, allowing you to perform
                        better in your personal and professional life. When
                        you're well-rested and energized, you're more motivated
                        to tackle tasks.
                      </li>
                      <li>
                        <strong className="text-[#060C14]">
                          Improved Relationships:
                        </strong>{" "}
                        When you prioritize self-care and your own well-being,
                        you have more energy, patience, and resources to invest
                        in your relationships and connect with others more
                        effectively.
                      </li>
                      <li>
                        <strong className="text-[#060C14]">
                          Better Physical Health:
                        </strong>{" "}
                        Engaging in regular exercise, healthy eating, and other
                        self-care practices can improve physical health, boost
                        your immune system, and reduce the risk of chronic
                        diseases.
                      </li>
                    </ul>
                  </section>

                  {/* High Fidelity Blockquote */}
                  <blockquote className="my-16 py-12 border-t border-b border-gray-100 flex flex-col items-center text-center">
                    <p className="text-[24px] italic leading-[1.6] text-[#060C14] font-prata max-w-2xl px-4">
                      "Self-care is not selfish. It's essential for maintaining
                      balance, managing stress, and preserving your well-being
                      in a busy and demanding world."
                    </p>
                    <div className="mt-6 flex items-center gap-3">
                      <span className="w-8 h-[1px] bg-gray-200" />
                      <span className="text-[10px] uppercase tracking-[0.3em] text-gray-400 font-bold">
                        Inspiration
                      </span>
                    </div>
                  </blockquote>

                  <section
                    id="practical-strategies-for-self-care"
                    className="scroll-mt-32"
                  >
                    <h2 className="text-[24px] font-prata text-[#060C14] mb-6">
                      Practical Strategies for Self-Care
                    </h2>
                    <p className="text-[16px] leading-[1.8] text-gray-600 mb-6">
                      Incorporating self-care into your daily routine doesn't
                      have to be complicated or time-consuming. Here are some
                      practical strategies for finding balance in a busy world:
                    </p>
                    <ul className="list-decimal pl-6 space-y-4 text-[16px] leading-[1.8] text-gray-600">
                      <li>
                        <strong className="text-[#060C14]">
                          Set Boundaries:
                        </strong>{" "}
                        Learn to say no to more activities or commitments that
                        drain your energy and make time for the things that
                        truly matter to you and bring you peace.
                      </li>
                      <li>
                        <strong className="text-[#060C14]">
                          Make Time for Activities You Enjoy:
                        </strong>{" "}
                        Schedule regular time for activities that bring you joy
                        and relaxation, whether it's reading, gardening, or
                        spending time in nature.
                      </li>
                      <li>
                        <strong className="text-[#060C14]">
                          Practice Mindfulness:
                        </strong>{" "}
                        Incorporate mindfulness practices such as meditation,
                        yoga, or deep breathing into your daily routine to help
                        reduce stress and improve well-being.
                      </li>
                      <li>
                        <strong className="text-[#060C14]">
                          Get Enough Sleep:
                        </strong>{" "}
                        Prioritize quality sleep by establishing a regular sleep
                        schedule and creating a relaxing bedtime routine to
                        ensure you're well-rested and energized for the day
                        ahead.
                      </li>
                      <li>
                        <strong className="text-[#060C14]">
                          Seek Support:
                        </strong>{" "}
                        Don't hesitate to reach out for support from friends,
                        family, or professionals if you're feeling overwhelmed
                        or struggling to balance self-care with other
                        responsibilities.
                      </li>
                    </ul>
                  </section>

                  <section id="conclusion" className="scroll-mt-32">
                    <h2 className="text-[24px] font-prata text-[#060C14] mb-6">
                      Conclusion
                    </h2>
                    <p className="text-[16px] leading-[1.8] text-gray-600 mb-6">
                      Finding balance and prioritizing self-care in a busy world
                      requires intention, commitment, and self-awareness. By
                      making self-care a priority and incorporating practical
                      strategies into your daily life, you can cultivate
                      resilience, manage stress, and nurture your overall
                      well-being.
                    </p>
                    <p className="text-[16px] leading-[1.8] text-gray-600 font-semibold text-[#060C14]">
                      Ready to prioritize self-care and find balance in your
                      busy world? Start implementing these strategies today and
                      watch as your health and happiness flourish.
                    </p>
                  </section>
                </div>

                <div className="mt-16 pt-8 border-t border-gray-100 flex flex-col sm:flex-row sm:items-center justify-between gap-6">
                  <div className="flex items-center gap-4">
                    <span className="text-[10px] font-bold uppercase tracking-widest text-gray-400">
                      Share this post
                    </span>
                    <div className="flex gap-4">
                      {["fb", "tw", "ln"].map((s) => (
                        <div
                          key={s}
                          className="w-8 h-8 rounded-full border border-gray-100 flex items-center justify-center hover:bg-[#ff4848] hover:text-white transition-all cursor-pointer"
                        >
                          <span className="uppercase text-[9px] font-bold">
                            {s}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              {/* Author Bio Section */}
              <div className="mt-24 p-8 sm:p-12 bg-[#F5F2ED] rounded-[40px] flex flex-col sm:flex-row gap-8 items-center sm:items-start text-center sm:text-left group">
                <div className="w-40 h-40 rounded-[30px] overflow-hidden flex-shrink-0 shadow-xl">
                  <img
                    src="https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=300&h=300&fit=crop"
                    alt="Kathryn Jackson"
                    className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
                  />
                </div>
                <div>
                  <h4 className="text-[24px] font-prata mb-2 text-[#060C14]">
                    Kathryn Jackson
                  </h4>
                  <p className="text-[#ff4848] text-[10px] font-bold uppercase tracking-[0.3em] mb-6">
                    Technologist & Writer
                  </p>
                  <p className="text-gray-500 text-[16px] leading-relaxed mb-10 max-w-xl italic">
                    Kathryn Jackson is a passionate writer with a knack for
                    weaving captivating stories. Her interests span across
                    travel, history, and the culinary arts. When not crafting
                    compelling content, you can find her exploring hidden gems.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#060C14] hover:text-[#ff4848] transition-colors group/link"
                  >
                    <span>Read Posts of - Kathryn Jackson</span>
                    <div className="w-10 h-10 rounded-full border border-gray-200 flex items-center justify-center group-hover/link:bg-[#060C14] group-hover/link:text-white transition-all">
                      <svg
                        width="12"
                        height="12"
                        viewBox="0 0 19 19"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M1.33008 17.4023L17.3301 1.40234M17.3301 1.40234H2.93008M17.3301 1.40234V15.8023"
                          stroke="currentColor"
                          strokeWidth="2.5"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        />
                      </svg>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Sidebar Column: Scroll Spy Nav */}
            <div className="lg:w-4/12 xl:w-3/12 hidden lg:block relative">
              <motion.div ref={sidebarRef} style={{ y: sidebarY }} className="space-y-16">
                <div>
                  <h4 className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#060C14] mb-10 pb-4 border-b border-[#F0EBE6] flex items-center gap-4">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#ff4848]" />
                    In this story
                  </h4>
                  <nav>
                    <ul className="space-y-8">
                      {mockToc.map((item) => (
                        <li
                          key={item.id}
                          className="group flex items-center gap-4"
                        >
                          {/* Scroll Indicator */}
                          <span
                            className={`h-[2px] bg-[#ff4848] transition-all duration-300 ${activeSection === item.id ? "w-5" : "w-0"}`}
                          />
                          <Link
                            href={`#${item.id}`}
                            onClick={(e) => {
                              e.preventDefault();
                              const target = document.getElementById(item.id);
                              if (target) {
                                window.scrollTo({
                                  top: target.offsetTop - 100,
                                  behavior: "smooth",
                                });
                              }
                            }}
                            className={`text-[11px] font-bold uppercase tracking-[0.2em] transition-all duration-300 ${activeSection === item.id ? "text-[#ff4848] translate-x-1" : "text-gray-400 hover:text-[#ff4848]"}`}
                          >
                            {item.title}
                          </Link>
                        </li>
                      ))}
                    </ul>
                  </nav>
                </div>

                <div className="p-10 bg-[#060C14] text-white rounded-[40px] relative overflow-hidden group">
                  <div className="relative z-10">
                    <h5 className="text-[24px] font-prata mb-6">
                      Join our newsletter
                    </h5>
                    <p className="text-[16px] text-gray-400 mb-8 leading-relaxed font-light italic">
                      Stay updated with the latest insights from global leaders.
                    </p>
                    <div className="relative">
                      <input
                        type="email"
                        placeholder="Email Address"
                        className="w-full bg-[#1A1A1A] border-0 rounded-full py-4 px-6 text-[10px] font-bold tracking-widest text-white focus:ring-1 focus:ring-[#ff4848] transition-all"
                      />
                      <button className="absolute right-2 top-1.5 bottom-1.5 w-10 h-10 rounded-full bg-[#ff4848] flex items-center justify-center hover:bg-white hover:text-[#ff4848] transition-colors">
                        <svg
                          width="12"
                          height="12"
                          viewBox="0 0 16 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M4 12L12 4M12 4H6M12 4V10"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          />
                        </svg>
                      </button>
                    </div>
                  </div>
                  <EyoloCornerRound className="absolute -bottom-10 -right-10 w-32 h-32 text-white/5 rotate-180" />
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      </div>

      <section className="py-24 border-t border-[#F0EBE6] bg-white">
        <div className="container mx-auto px-6">
          <div className="flex flex-col sm:flex-row justify-between items-end mb-16 gap-6">
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.5em] text-[#ff4848] mb-6 pl-4 relative after:absolute after:rounded-full after:h-1.5 after:w-1.5 after:bg-[#ff4848] after:left-0 after:top-1/2 after:-translate-y-1/2">
                Suggested Posts
              </p>
              <h2 className="text-[24px] font-prata text-[#060C14]">
                Continue Reading
              </h2>
            </div>
            <Link
              href={`/${locale}/blog`}
              className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#060C14] border-b border-[#060C14] pb-1 hover:text-[#ff4848] hover:border-[#ff4848] transition-all"
            >
              All Posts
            </Link>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {suggestedPosts.map((post) => (
              <div key={post.id} className="group">
                <div className="relative aspect-[4/3] rounded-2xl overflow-hidden mb-8">
                  <img
                    src={post.image}
                    className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-[1.5s]"
                    alt={post.title}
                  />
                  <div className="absolute top-4 left-4">
                    <span className="bg-white/95 text-[#ff4848] text-[9px] font-bold uppercase tracking-widest px-3 py-1.5 rounded-md shadow-sm">
                      {post.category}
                    </span>
                  </div>
                </div>
                <p className="text-[9px] font-bold uppercase tracking-widest text-gray-400 mb-4">
                  {post.date}
                </p>
                <h3 className="text-[24px] font-prata !leading-tight text-[#060C14] hover:text-[#ff4848] transition-colors mb-4 line-clamp-2">
                  {post.title}
                </h3>
                <div className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-widest text-gray-400">
                  <span>By {post.author}</span>
                  <span className="opacity-40">•</span>
                  <span>{post.readTime}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer / Get In Touch */}
      <section className="py-24 sm:py-32 bg-[#060C14] text-white overflow-hidden border-t border-white/5">
        <div className="container mx-auto px-6 text-center lg:text-left">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-16 items-center border-b border-white/10 pb-20 mb-12">
            <div className="lg:col-span-8">
              <h2 className="text-[29px] font-prata text-white mb-8">
                Get In Touch
              </h2>
              <p className="text-gray-400 text-[16px] leading-relaxed max-w-2xl font-light opacity-80 italic mx-auto lg:mx-0">
                Feel free to reach out with questions or specific project
                inquiries. Our consultants are ready to help.
              </p>
            </div>
            <div className="lg:col-span-4 flex flex-col items-center lg:items-end gap-12">
              <div className="text-center lg:text-right">
                <p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#ff4848] mb-4">
                  Contact
                </p>
                <p className="text-[24px] font-prata">+1 (555) 123-4567</p>
              </div>
              <div className="text-center lg:text-right">
                <p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#ff4848] mb-4">
                  Email
                </p>
                <p className="text-[24px] font-prata">hello@busrom.com</p>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap items-center justify-center lg:justify-start gap-8 lg:gap-16 text-[10px] font-bold uppercase tracking-[0.4em] text-gray-600">
            <Link href="#" className="hover:text-white transition-colors">
              About
            </Link>
            <Link href="#" className="hover:text-white transition-colors">
              Archive
            </Link>
            <Link href="#" className="hover:text-white transition-colors">
              Contact
            </Link>
            <Link href="#" className="hover:text-white transition-colors">
              Privacy Policy
            </Link>
          </div>
        </div>
      </section>
    </article>
  );
}
