/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'media-categories': MediaCategory;
    'media-tags': MediaTag;
    roles: Role;
    permissions: Permission;
    'activity-logs': ActivityLog;
    products: Product;
    'product-series': ProductSery;
    'hero-banner-items': HeroBannerItem;
    'series-intro-items': SeriesIntroItem;
    'navigation-menus': NavigationMenu;
    pages: Page;
    blogs: Blog;
    applications: Application;
    categories: Category;
    'faq-items': FaqItem;
    'reusable-blocks': ReusableBlock;
    'document-templates': DocumentTemplate;
    'custom-scripts': CustomScript;
    'seo-settings': SeoSetting;
    'form-configs': FormConfig;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    roles: {
      users: 'users';
    };
    permissions: {
      roles: 'roles';
      users: 'users';
    };
    'product-series': {
      products: 'products';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-categories': MediaCategoriesSelect<false> | MediaCategoriesSelect<true>;
    'media-tags': MediaTagsSelect<false> | MediaTagsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    'activity-logs': ActivityLogsSelect<false> | ActivityLogsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-series': ProductSeriesSelect<false> | ProductSeriesSelect<true>;
    'hero-banner-items': HeroBannerItemsSelect<false> | HeroBannerItemsSelect<true>;
    'series-intro-items': SeriesIntroItemsSelect<false> | SeriesIntroItemsSelect<true>;
    'navigation-menus': NavigationMenusSelect<false> | NavigationMenusSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'reusable-blocks': ReusableBlocksSelect<false> | ReusableBlocksSelect<true>;
    'document-templates': DocumentTemplatesSelect<false> | DocumentTemplatesSelect<true>;
    'custom-scripts': CustomScriptsSelect<false> | CustomScriptsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    'form-configs': FormConfigsSelect<false> | FormConfigsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | (
        | 'en'
        | 'zh'
        | 'es'
        | 'fr'
        | 'de'
        | 'ja'
        | 'ko'
        | 'pt'
        | 'it'
        | 'nl'
        | 'pl'
        | 'ru'
        | 'ar'
        | 'th'
        | 'vi'
        | 'id'
        | 'ms'
        | 'tr'
        | 'hi'
        | 'bn'
        | 'sv'
        | 'da'
        | 'no'
        | 'fi'
      )
    | (
        | 'en'
        | 'zh'
        | 'es'
        | 'fr'
        | 'de'
        | 'ja'
        | 'ko'
        | 'pt'
        | 'it'
        | 'nl'
        | 'pl'
        | 'ru'
        | 'ar'
        | 'th'
        | 'vi'
        | 'id'
        | 'ms'
        | 'tr'
        | 'hi'
        | 'bn'
        | 'sv'
        | 'da'
        | 'no'
        | 'fi'
      )[];
  globals: {
    'home-content': HomeContent;
    footer: Footer;
    'site-config': SiteConfig;
    'contact-config': ContactConfig;
    'social-config': SocialConfig;
    'product-series-carousel': ProductSeriesCarousel;
    'service-features': ServiceFeature;
    'sphere-3d': Sphere3D;
    'simple-cta': SimpleCta;
    'featured-products': FeaturedProduct;
    'brand-advantages': BrandAdvantage;
    'oem-odm': OemOdm;
    'quote-steps': QuoteStep;
    'main-form': MainForm;
    'why-choose-busrom': WhyChooseBusrom;
    'case-studies': CaseStudy;
    'brand-analysis': BrandAnalysis;
    'brand-value': BrandValue;
    'email-config': EmailConfig;
    'translation-config': TranslationConfig;
  };
  globalsSelect: {
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    'contact-config': ContactConfigSelect<false> | ContactConfigSelect<true>;
    'social-config': SocialConfigSelect<false> | SocialConfigSelect<true>;
    'product-series-carousel': ProductSeriesCarouselSelect<false> | ProductSeriesCarouselSelect<true>;
    'service-features': ServiceFeaturesSelect<false> | ServiceFeaturesSelect<true>;
    'sphere-3d': Sphere3DSelect<false> | Sphere3DSelect<true>;
    'simple-cta': SimpleCtaSelect<false> | SimpleCtaSelect<true>;
    'featured-products': FeaturedProductsSelect<false> | FeaturedProductsSelect<true>;
    'brand-advantages': BrandAdvantagesSelect<false> | BrandAdvantagesSelect<true>;
    'oem-odm': OemOdmSelect<false> | OemOdmSelect<true>;
    'quote-steps': QuoteStepsSelect<false> | QuoteStepsSelect<true>;
    'main-form': MainFormSelect<false> | MainFormSelect<true>;
    'why-choose-busrom': WhyChooseBusromSelect<false> | WhyChooseBusromSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'brand-analysis': BrandAnalysisSelect<false> | BrandAnalysisSelect<true>;
    'brand-value': BrandValueSelect<false> | BrandValueSelect<true>;
    'email-config': EmailConfigSelect<false> | EmailConfigSelect<true>;
    'translation-config': TranslationConfigSelect<false> | TranslationConfigSelect<true>;
  };
  locale:
    | 'en'
    | 'zh'
    | 'es'
    | 'fr'
    | 'de'
    | 'ja'
    | 'ko'
    | 'pt'
    | 'it'
    | 'nl'
    | 'pl'
    | 'ru'
    | 'ar'
    | 'th'
    | 'vi'
    | 'id'
    | 'ms'
    | 'tr'
    | 'hi'
    | 'bn'
    | 'sv'
    | 'da'
    | 'no'
    | 'fi';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Assign one or more roles to this user
   */
  roles?: (number | Role)[] | null;
  /**
   * Grant additional permissions beyond role permissions
   */
  directPermissions?: (number | Permission)[] | null;
  /**
   * Super admin has full access to all system features
   */
  isAdmin?: boolean | null;
  status?: ('active' | 'inactive' | 'suspended') | null;
  lastLogin?: string | null;
  twoFactorEnabled?: boolean | null;
  twoFactorSecret?: string | null;
  backupCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * User roles with permission assignments
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  /**
   * Unique identifier, e.g., "content_editor", "product_manager"
   */
  code: string;
  description?: string | null;
  /**
   * Select permissions for this role
   */
  permissions?: (number | Permission)[] | null;
  /**
   * Inherit permissions from parent role
   */
  parentRole?: (number | null) | Role;
  /**
   * Users assigned to this role
   */
  users?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Priority for resolving permission conflicts (1-10, higher is better)
   */
  priority?: number | null;
  /**
   * System roles cannot be deleted
   */
  isSystem?: boolean | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * System permissions for role-based access control
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  /**
   * The resource this permission applies to
   */
  resource:
    | 'USER'
    | 'ROLE'
    | 'PERMISSION'
    | 'ACTIVITY_LOG'
    | 'PRODUCT'
    | 'PRODUCT_SERIES'
    | 'PAGE'
    | 'BLOG'
    | 'APPLICATION'
    | 'CATEGORY'
    | 'FAQ_ITEM'
    | 'REUSABLE_BLOCK'
    | 'DOCUMENT_TEMPLATE'
    | 'NAVIGATION_MENU'
    | 'HERO_BANNER_ITEM'
    | 'MEDIA'
    | 'MEDIA_CATEGORY'
    | 'MEDIA_TAG'
    | 'FORM_CONFIG'
    | 'FORM_SUBMISSION'
    | 'HOME_CONTENT'
    | 'FOOTER'
    | 'HOMEPAGE_GLOBAL'
    | 'SITE_CONFIG'
    | 'SEO_SETTING'
    | 'CUSTOM_SCRIPT'
    | 'EMAIL_CONFIG'
    | 'CONTACT_CONFIG'
    | 'SOCIAL_CONFIG'
    | 'TRANSLATION_CONFIG';
  /**
   * The action allowed on the resource
   */
  action: 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'PUBLISH' | 'EXPORT' | 'IMPORT' | 'MANAGE';
  /**
   * Auto-generated: RESOURCE_ACTION
   */
  identifier?: string | null;
  /**
   * Group permissions by category
   */
  category?: ('USER' | 'CONTENT' | 'MEDIA' | 'FORMS' | 'HOMEPAGE' | 'SYSTEM') | null;
  /**
   * Optional description of what this permission allows
   */
  description?: string | null;
  /**
   * Roles that have this permission
   */
  roles?: {
    docs?: (number | Role)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Users with this permission directly assigned
   */
  users?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * System permissions are pre-defined and protected
   */
  isSystem?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * SEO-friendly alt text for images | 图片的SEO友好替代文本
   */
  alt: string;
  /**
   * Main category for this media | 此媒体的主分类
   */
  primaryCategory?: (number | null) | MediaCategory;
  /**
   * Tags for filtering and searching | 用于筛选和搜索的标签
   */
  tags?: (number | MediaTag)[] | null;
  metadata?: {
    /**
     * Scene group number for scene images | 场景图的分组编号
     */
    group?: number | null;
    sceneNumber?: number | null;
    /**
     * Image sequence number within a series/scene group | 该系列/场景分组内的图片序号
     */
    imageNumber?: number | null;
    /**
     * Product specifications for this image | 此图片的产品规格
     */
    specs?:
      | {
          key: 'color' | 'material' | 'size' | 'finish' | 'model' | 'series' | 'style' | 'other';
          value: string;
          customKey?: string | null;
          id?: string | null;
        }[]
      | null;
    notes?: string | null;
  };
  /**
   * Visual editor for image focal point | 可视化焦点编辑器
   */
  focalPointData?: {
    x?: number | null;
    y?: number | null;
  };
  /**
   * Media status (archived = soft delete) | 媒体状态（归档=软删除）
   */
  status?: ('active' | 'archived') | null;
  usageCount?: number | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  /**
   * Media file name | 媒体文件名
   */
  filename: string;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-categories".
 */
export interface MediaCategory {
  id: number;
  /**
   * Internal identifier (e.g., "product-images") | 内部标识符（如 "product-images"）
   */
  name: string;
  /**
   * User-friendly name shown in UI | 在界面中显示的友好名称
   */
  displayName: string;
  description?: string | null;
  /**
   * Icon name or emoji | 图标名称或 emoji
   */
  icon?: string | null;
  /**
   * Color code for UI display (e.g., #3498db) | UI显示的颜色代码
   */
  color?: string | null;
  /**
   * Display order in lists | 列表中的显示顺序
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-tags".
 */
export interface MediaTag {
  id: number;
  name: string;
  /**
   * Type of tag for grouping | 标签分组类型
   */
  type: 'general' | 'product_series' | 'product_model' | 'scene' | 'color' | 'material' | 'style';
  /**
   * Optional category this tag belongs to | 此标签所属的可选分类
   */
  category?: (number | null) | MediaCategory;
  description?: string | null;
  /**
   * Color code for UI display | UI显示的颜色代码
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * System activity audit trail
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs".
 */
export interface ActivityLog {
  id: number;
  user?: (number | null) | User;
  /**
   * Stored for reference even if user is deleted
   */
  userName?: string | null;
  userEmail?: string | null;
  action:
    | 'CREATE'
    | 'UPDATE'
    | 'DELETE'
    | 'LOGIN'
    | 'LOGOUT'
    | 'PUBLISH'
    | 'UNPUBLISH'
    | 'EXPORT'
    | 'IMPORT'
    | 'RESTORE'
    | 'DUPLICATE'
    | 'BULK_UPDATE'
    | 'BULK_DELETE';
  entity:
    | 'USER'
    | 'ROLE'
    | 'PERMISSION'
    | 'MEDIA'
    | 'PRODUCT'
    | 'PRODUCT_SERIES'
    | 'PAGE'
    | 'BLOG'
    | 'APPLICATION'
    | 'CATEGORY'
    | 'FAQ_ITEM'
    | 'REUSABLE_BLOCK'
    | 'NAVIGATION_MENU'
    | 'HERO_BANNER_ITEM'
    | 'SITE_CONFIG'
    | 'SEO_SETTING'
    | 'CUSTOM_SCRIPT'
    | 'FORM_CONFIG'
    | 'FORM_SUBMISSION'
    | 'FOOTER'
    | 'HOME_CONTENT'
    | 'EMAIL_CONFIG'
    | 'SYSTEM';
  entityId?: string | null;
  /**
   * Human-readable title of the affected entity
   */
  entityTitle?: string | null;
  /**
   * Human-readable summary of the action
   */
  summary?: string | null;
  /**
   * JSON object containing before/after values
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional context about the action
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Product model code (e.g., "GDH-001")
   */
  sku: string;
  /**
   * URL-friendly identifier (auto-generated if empty)
   */
  slug: string;
  name: string;
  /**
   * Brief product description for listings
   */
  shortDescription?: string | null;
  /**
   * Detailed product description
   */
  description?: string | null;
  /**
   * Series this product belongs to
   */
  series?: (number | null) | ProductSery;
  /**
   * Rich text content - use language tabs above to switch locales
   */
  contentTranslation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Product attributes (key-value pairs)
   */
  attributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Product variants (colors, sizes, etc.)
   */
  specifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Product list display image
   */
  showImage?: (number | null) | Media;
  /**
   * Product detail page images (gallery with hover carousel)
   */
  mainImage?: (number | Media)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  status?: ('published' | 'draft' | 'archived') | null;
  isFeatured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-series".
 */
export interface ProductSery {
  id: number;
  /**
   * URL-friendly identifier (e.g., "elite-door-handle-series")
   */
  slug: string;
  /**
   * Product series name (localized)
   */
  name: string;
  /**
   * Brief series description (localized)
   */
  description?: string | null;
  /**
   * Primary category for this product series
   */
  category?: (number | null) | Category;
  /**
   * Rich text content - use language tabs above to switch locales
   */
  contentTranslation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Main image for this series
   */
  featuredImage?: (number | null) | Media;
  /**
   * Products in this series
   */
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  status?: ('published' | 'draft' | 'archived') | null;
  /**
   * Lower number = higher priority
   */
  order?: number | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g., "door-hardware")
   */
  slug: string;
  type: 'PAGE' | 'PRODUCT' | 'BLOG' | 'APPLICATION' | 'FAQ';
  /**
   * Parent category for hierarchical structure
   */
  parent?: (number | null) | Category;
  description?: string | null;
  /**
   * Lower number = higher priority
   */
  order?: number | null;
  status?: ('published' | 'draft' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banner-items".
 */
export interface HeroBannerItem {
  id: number;
  /**
   * Internal identifier for this banner item (e.g., "Banner 1 - Glass Standoff")
   */
  internalLabel: string;
  title: string;
  feature1: string;
  feature2: string;
  feature3: string;
  feature4: string;
  feature5: string;
  /**
   * Select an image | 选择一张图片
   */
  image1?: (number | null) | Media;
  image2?: (number | null) | Media;
  image3?: (number | null) | Media;
  image4?: (number | null) | Media;
  ctaButton?: {
    text?: string | null;
    link?: string | null;
  };
  order?: number | null;
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series-intro-items".
 */
export interface SeriesIntroItem {
  id: number;
  /**
   * Internal identifier for this series intro item
   */
  internalLabel: string;
  /**
   * Link to a product series
   */
  productSeries?: (number | null) | ProductSery;
  title?: string | null;
  description?: string | null;
  /**
   * Choose manual selection (up to 5 images) or auto random by category/tags
   */
  images?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus".
 */
export interface NavigationMenu {
  id: number;
  /**
   * 唯一标识符，例如: product, service, about-us
   */
  slug: string;
  name: string;
  type: 'standard' | 'product_cards' | 'submenu';
  /**
   * Lucide-react 图标名称，例如: Home, Package, Wrench
   */
  icon?: string | null;
  /**
   * 选择标签筛选图片，用于 PRODUCT_CARDS 类型
   */
  mediaTags?: (number | MediaTag)[] | null;
  /**
   * 留空表示顶级菜单
   */
  parent?: (number | null) | NavigationMenu;
  /**
   * 外链 https://... 或内部路径 /product, /service
   */
  link?: string | null;
  /**
   * "询单"按钮的链接，仅用于 PRODUCT_CARDS 类型
   */
  inquiryLink?: string | null;
  /**
   * 数字越小越靠前
   */
  order?: number | null;
  /**
   * 系统默认菜单，不可删除
   */
  isSystem?: boolean | null;
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Unified page management - includes template pages and freeform landing pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * CMS internal identifier. e.g.: service-overview, faq, summer-promotion-2024
   */
  slug: string;
  /**
   * Full URL path for frontend routing. e.g.: /service/one-stop-shop, /about-us/story
   */
  path: string;
  /**
   * Template: fixed structure, only edit content | Freeform: fully customizable
   */
  pageType: 'TEMPLATE' | 'FREEFORM';
  /**
   * Only for template pages. e.g.: SERVICE_OVERVIEW, FAQ, ABOUT_US, OEM_ODM
   */
  template?: string | null;
  title: string;
  /**
   * Rich text content - use language tabs above to switch locales
   */
  contentTranslation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select media tags for hero waterfall animation
   */
  heroMediaTags?: (number | MediaTag)[] | null;
  heroText?: string | null;
  heroSubtitle?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * System pages cannot be deleted
   */
  isSystem?: boolean | null;
  status?: ('published' | 'draft' | 'archived') | null;
  publishedAt?: string | null;
  /**
   * Lower number = higher priority
   */
  order?: number | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  /**
   * URL-friendly identifier (e.g., "how-to-install-glass-standoff")
   */
  slug: string;
  title: string;
  /**
   * Short summary for previews and SEO
   */
  excerpt?: string | null;
  author?: string | null;
  /**
   * Rich text content - use language tabs above to switch locales
   */
  contentTranslation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  /**
   * Select blog categories
   */
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  status?: ('published' | 'draft' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  /**
   * URL-friendly identifier (e.g., "commercial-building-glass-railing")
   */
  slug: string;
  name: string;
  shortDescription?: string | null;
  description?: string | null;
  category?: (number | null) | Category;
  /**
   * Manage scene image groups. Each scene can contain multiple images.
   */
  sceneGallery?:
    | {
        sceneName: string;
        /**
         * Select multiple images for this scene
         */
        images?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  status?: ('published' | 'draft' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  /**
   * Unique identifier (e.g., "shipping-policy")
   */
  slug: string;
  question: string;
  /**
   * Rich text answer - use language tabs above to switch locales
   */
  contentTranslation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select an FAQ category
   */
  category?: (number | null) | Category;
  /**
   * Link to related FAQ items
   */
  relatedFaqs?: (number | FaqItem)[] | null;
  /**
   * Lower number = higher priority
   */
  order?: number | null;
  status?: ('published' | 'draft' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-blocks".
 */
export interface ReusableBlock {
  id: number;
  /**
   * Unique identifier (e.g., "cta-contact-us", "feature-quality")
   */
  slug: string;
  blockType: 'CTA' | 'FEATURE' | 'TESTIMONIAL' | 'CONTACT' | 'CUSTOM';
  title?: string | null;
  subtitle?: string | null;
  /**
   * Rich text content - use language tabs above to switch locales
   */
  contentTranslation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('published' | 'draft' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pre-made content templates that can be inserted into documents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-templates".
 */
export interface DocumentTemplate {
  id: number;
  /**
   * Unique identifier (e.g., "product-intro-template")
   */
  key: string;
  name: string;
  description?: string | null;
  /**
   * Category for organizing templates
   */
  category?: ('product-intro' | 'feature' | 'faq' | 'testimonial' | 'cta' | 'comparison' | 'other') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Comma-separated tags for searching (e.g., "product, hero, banner")
   */
  tags?: string | null;
  /**
   * Number of times this template has been used
   */
  usageCount?: number | null;
  /**
   * Only ACTIVE templates appear in the template selector
   */
  status?: ('active' | 'draft' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage tracking scripts and custom code injection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-scripts".
 */
export interface CustomScript {
  id: number;
  /**
   * e.g., "Google Analytics", "TikTok Pixel"
   */
  name: string;
  description?: string | null;
  scriptPosition: 'header' | 'footer' | 'body_start';
  /**
   * Enter complete <script> tag or other code
   */
  content: string;
  scope: 'global' | 'page_type' | 'exact_path' | 'path_pattern';
  pageType?:
    | (
        | 'home'
        | 'product_series_list'
        | 'product_series_detail'
        | 'shop_list'
        | 'shop_detail'
        | 'blog_list'
        | 'blog_detail'
        | 'application_list'
        | 'application_detail'
      )
    | null;
  /**
   * e.g., /about-us/contact
   */
  exactPath?: string | null;
  /**
   * e.g., /product/* or /blog/**
   */
  pathPattern?: string | null;
  isEnabled?: boolean | null;
  /**
   * Higher number = loads first
   */
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SEO configuration for pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  /**
   * Unique identifier for this SEO setting
   */
  identifier: string;
  scope: 'global' | 'page_type' | 'exact_path' | 'path_pattern';
  pageType?:
    | (
        | 'home'
        | 'product_series_list'
        | 'product_series_detail'
        | 'shop_list'
        | 'shop_detail'
        | 'blog_list'
        | 'blog_detail'
        | 'application_list'
        | 'application_detail'
      )
    | null;
  exactPath?: string | null;
  /**
   * e.g., /product/* or /blog/**
   */
  pathPattern?: string | null;
  /**
   * Override page title for SEO
   */
  metaTitle?: string | null;
  /**
   * 150-160 characters recommended
   */
  metaDescription?: string | null;
  /**
   * Comma-separated keywords
   */
  metaKeywords?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImage?: (number | null) | Media;
  ogType?: ('website' | 'article' | 'product') | null;
  robotsIndex?: boolean | null;
  robotsFollow?: boolean | null;
  /**
   * Leave empty to use default page URL
   */
  canonicalUrl?: string | null;
  includeInSitemap?: boolean | null;
  /**
   * 0.0 - 1.0
   */
  sitemapPriority?: number | null;
  sitemapChangefreq?: ('always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure dynamic form fields
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-configs".
 */
export interface FormConfig {
  id: number;
  /**
   * e.g., "main-form", "footer-form", "contact-us-form"
   */
  name: string;
  displayName?: string | null;
  description?: string | null;
  location: 'HOME_MAIN' | 'FOOTER' | 'CONTACT_US' | 'QUICK_INQUIRY' | 'CUSTOM';
  /**
   * Configure dynamic form fields
   */
  fields?:
    | {
        /**
         * Internal field name (e.g., "email", "company")
         */
        fieldName: string;
        label: string;
        placeholder?: string | null;
        fieldType:
          | 'text'
          | 'email'
          | 'phone'
          | 'textarea'
          | 'select'
          | 'checkbox'
          | 'radio'
          | 'number'
          | 'date'
          | 'file';
        options?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        required?: boolean | null;
        width?: ('full' | 'half' | 'third') | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  submitButtonText?: string | null;
  successMessage?: string | null;
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * View and manage form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  /**
   * The form configuration this submission belongs to
   */
  formConfig?: (number | null) | FormConfig;
  /**
   * Auto-populated from form config
   */
  formName?: string | null;
  /**
   * All submitted form field values
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * List of uploaded files
   */
  attachments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Total size of all attachments in bytes
   */
  totalAttachmentSize?: number | null;
  status: 'UNREAD' | 'READ' | 'ARCHIVED';
  submissionType?: ('MANUAL' | 'AUTO') | null;
  /**
   * Language at time of submission
   */
  locale?: string | null;
  /**
   * Page URL where form was submitted
   */
  sourcePage?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  /**
   * Internal notes about this submission
   */
  adminNotes?: string | null;
  /**
   * Whether notification email has been sent
   */
  emailSent?: boolean | null;
  submittedAt?: string | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-categories';
        value: number | MediaCategory;
      } | null)
    | ({
        relationTo: 'media-tags';
        value: number | MediaTag;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'permissions';
        value: number | Permission;
      } | null)
    | ({
        relationTo: 'activity-logs';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-series';
        value: number | ProductSery;
      } | null)
    | ({
        relationTo: 'hero-banner-items';
        value: number | HeroBannerItem;
      } | null)
    | ({
        relationTo: 'series-intro-items';
        value: number | SeriesIntroItem;
      } | null)
    | ({
        relationTo: 'navigation-menus';
        value: number | NavigationMenu;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'reusable-blocks';
        value: number | ReusableBlock;
      } | null)
    | ({
        relationTo: 'document-templates';
        value: number | DocumentTemplate;
      } | null)
    | ({
        relationTo: 'custom-scripts';
        value: number | CustomScript;
      } | null)
    | ({
        relationTo: 'seo-settings';
        value: number | SeoSetting;
      } | null)
    | ({
        relationTo: 'form-configs';
        value: number | FormConfig;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  directPermissions?: T;
  isAdmin?: T;
  status?: T;
  lastLogin?: T;
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  backupCodes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  primaryCategory?: T;
  tags?: T;
  metadata?:
    | T
    | {
        group?: T;
        sceneNumber?: T;
        imageNumber?: T;
        specs?:
          | T
          | {
              key?: T;
              value?: T;
              customKey?: T;
              id?: T;
            };
        notes?: T;
      };
  focalPointData?:
    | T
    | {
        x?: T;
        y?: T;
      };
  status?: T;
  usageCount?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-categories_select".
 */
export interface MediaCategoriesSelect<T extends boolean = true> {
  name?: T;
  displayName?: T;
  description?: T;
  icon?: T;
  color?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-tags_select".
 */
export interface MediaTagsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  category?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  description?: T;
  permissions?: T;
  parentRole?: T;
  users?: T;
  priority?: T;
  isSystem?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  resource?: T;
  action?: T;
  identifier?: T;
  category?: T;
  description?: T;
  roles?: T;
  users?: T;
  isSystem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs_select".
 */
export interface ActivityLogsSelect<T extends boolean = true> {
  user?: T;
  userName?: T;
  userEmail?: T;
  action?: T;
  entity?: T;
  entityId?: T;
  entityTitle?: T;
  summary?: T;
  changes?: T;
  metadata?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  sku?: T;
  slug?: T;
  name?: T;
  shortDescription?: T;
  description?: T;
  series?: T;
  contentTranslation?: T;
  attributes?: T;
  specifications?: T;
  showImage?: T;
  mainImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  status?: T;
  isFeatured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-series_select".
 */
export interface ProductSeriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  category?: T;
  contentTranslation?: T;
  featuredImage?: T;
  products?: T;
  status?: T;
  order?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banner-items_select".
 */
export interface HeroBannerItemsSelect<T extends boolean = true> {
  internalLabel?: T;
  title?: T;
  feature1?: T;
  feature2?: T;
  feature3?: T;
  feature4?: T;
  feature5?: T;
  image1?: T;
  image2?: T;
  image3?: T;
  image4?: T;
  ctaButton?:
    | T
    | {
        text?: T;
        link?: T;
      };
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series-intro-items_select".
 */
export interface SeriesIntroItemsSelect<T extends boolean = true> {
  internalLabel?: T;
  productSeries?: T;
  title?: T;
  description?: T;
  images?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus_select".
 */
export interface NavigationMenusSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  type?: T;
  icon?: T;
  mediaTags?: T;
  parent?: T;
  link?: T;
  inquiryLink?: T;
  order?: T;
  isSystem?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  path?: T;
  pageType?: T;
  template?: T;
  title?: T;
  contentTranslation?: T;
  heroMediaTags?: T;
  heroText?: T;
  heroSubtitle?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  isSystem?: T;
  status?: T;
  publishedAt?: T;
  order?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  author?: T;
  contentTranslation?: T;
  coverImage?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortDescription?: T;
  description?: T;
  category?: T;
  sceneGallery?:
    | T
    | {
        sceneName?: T;
        images?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  parent?: T;
  description?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  slug?: T;
  question?: T;
  contentTranslation?: T;
  category?: T;
  relatedFaqs?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-blocks_select".
 */
export interface ReusableBlocksSelect<T extends boolean = true> {
  slug?: T;
  blockType?: T;
  title?: T;
  subtitle?: T;
  contentTranslation?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-templates_select".
 */
export interface DocumentTemplatesSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  description?: T;
  category?: T;
  content?: T;
  tags?: T;
  usageCount?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-scripts_select".
 */
export interface CustomScriptsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  scriptPosition?: T;
  content?: T;
  scope?: T;
  pageType?: T;
  exactPath?: T;
  pathPattern?: T;
  isEnabled?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  identifier?: T;
  scope?: T;
  pageType?: T;
  exactPath?: T;
  pathPattern?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  ogType?: T;
  robotsIndex?: T;
  robotsFollow?: T;
  canonicalUrl?: T;
  includeInSitemap?: T;
  sitemapPriority?: T;
  sitemapChangefreq?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-configs_select".
 */
export interface FormConfigsSelect<T extends boolean = true> {
  name?: T;
  displayName?: T;
  description?: T;
  location?: T;
  fields?:
    | T
    | {
        fieldName?: T;
        label?: T;
        placeholder?: T;
        fieldType?: T;
        options?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        required?: T;
        width?: T;
        order?: T;
        id?: T;
      };
  submitButtonText?: T;
  successMessage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formConfig?: T;
  formName?: T;
  data?: T;
  attachments?: T;
  totalAttachmentSize?: T;
  status?: T;
  submissionType?: T;
  locale?: T;
  sourcePage?: T;
  ipAddress?: T;
  userAgent?: T;
  adminNotes?: T;
  emailSent?: T;
  submittedAt?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  /**
   * 配置首页各区块的显示顺序和状态
   */
  sections?:
    | {
        sectionType:
          | 'hero_banner'
          | 'product_series_carousel'
          | 'service_features'
          | 'sphere_3d'
          | 'simple_cta'
          | 'series_intro'
          | 'featured_products'
          | 'brand_advantages'
          | 'oem_odm'
          | 'quote_steps'
          | 'main_form'
          | 'why_choose_busrom'
          | 'case_studies'
          | 'brand_analysis'
          | 'brand_value';
        enabled?: boolean | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * 选择一个表单配置 (推荐使用 "footer-form")。如果选择了表单配置，将忽略下方的旧版字段设置。
   */
  formConfig?: (number | null) | FormConfig;
  /**
   * ⚠️ 旧版配置。如果使用了 FormConfig，此字段将被忽略。
   */
  formTitle?: string | null;
  /**
   * ⚠️ 旧版配置。
   */
  formPlaceholderName?: string | null;
  /**
   * ⚠️ 旧版配置。
   */
  formPlaceholderEmail?: string | null;
  /**
   * ⚠️ 旧版配置。
   */
  formPlaceholderMessage?: string | null;
  submitButtonText?: string | null;
  contactTitle?: string | null;
  /**
   * 例如: "Email", "联系邮箱" 等
   */
  contactEmailLabel?: string | null;
  contactEmail?: string | null;
  /**
   * 例如: "After-sales", "售后" 等
   */
  afterSalesLabel?: string | null;
  afterSalesEmail?: string | null;
  whatsappLabel?: string | null;
  whatsappNumber?: string | null;
  /**
   * ⚠️ 已弃用，请使用 contactEmail
   */
  email?: string | null;
  /**
   * ⚠️ 已弃用
   */
  phone?: string | null;
  whatsapp?: string | null;
  address?: string | null;
  workingHours?: string | null;
  officialNoticeTitle?: string | null;
  officialNoticeLine1?: string | null;
  officialNoticeLine2?: string | null;
  officialNoticeLine3?: string | null;
  /**
   * 例如：署名、日期等
   */
  officialNoticeLine4?: string | null;
  /**
   * ⚠️ 旧版字段，请使用上方的 Line 1-4
   */
  officialNoticeContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  socialLinks?:
    | {
        platform?:
          | ('facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok' | 'wechat' | 'whatsapp')
          | null;
        url: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 选择要在非首页页脚第三列显示的导航菜单（必须是有实际页面的菜单）
   */
  column3Menus?: (number | NavigationMenu)[] | null;
  /**
   * 选择要在非首页页脚第四列显示的导航菜单（必须是有实际页面的菜单）
   */
  column4Menus?: (number | NavigationMenu)[] | null;
  copyrightText?: string | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  siteName: string;
  siteTagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactAddress?: string | null;
  googleMapsUrl?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  googleAnalyticsId?: string | null;
  googleTagManagerId?: string | null;
  facebook?: string | null;
  twitter?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Company contact information settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-config".
 */
export interface ContactConfig {
  id: number;
  /**
   * Primary contact email
   */
  email?: string | null;
  /**
   * Primary contact phone number
   */
  phone?: string | null;
  /**
   * WhatsApp number for customer support
   */
  whatsapp?: string | null;
  /**
   * WeChat ID
   */
  wechat?: string | null;
  /**
   * Company physical address
   */
  address?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Social media links settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-config".
 */
export interface SocialConfig {
  id: number;
  /**
   * Facebook page URL
   */
  facebookUrl?: string | null;
  /**
   * Instagram profile URL
   */
  instagramUrl?: string | null;
  /**
   * LinkedIn company page URL
   */
  linkedinUrl?: string | null;
  /**
   * YouTube channel URL
   */
  youtubeUrl?: string | null;
  /**
   * Twitter/X profile URL
   */
  twitterUrl?: string | null;
  /**
   * TikTok profile URL
   */
  tiktokUrl?: string | null;
  /**
   * Pinterest profile URL
   */
  pinterestUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-series-carousel".
 */
export interface ProductSeriesCarousel {
  id: number;
  status?: ('draft' | 'published') | null;
  title?: string | null;
  /**
   * Multilingual carousel items. Each language has its own array of items.
   */
  items?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  autoplay?: boolean | null;
  autoplaySpeed?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-features".
 */
export interface ServiceFeature {
  id: number;
  status?: ('draft' | 'published') | null;
  /**
   * 例如: "Premium Architectural Glass Hardware"
   */
  title?: string | null;
  subtitle?: string | null;
  /**
   * 例如: "Any Size, Any Structure, Any Shape"
   */
  feature01Title?: string | null;
  /**
   * 例如: "Any Size"
   */
  feature01ShortTitle?: string | null;
  feature01Description?: string | null;
  feature01Image1?: (number | null) | Media;
  feature01Image2?: (number | null) | Media;
  feature01Image3?: (number | null) | Media;
  feature01Image4?: (number | null) | Media;
  feature02Title?: string | null;
  feature02ShortTitle?: string | null;
  feature02Description?: string | null;
  feature02Image1?: (number | null) | Media;
  feature02Image2?: (number | null) | Media;
  feature03Title?: string | null;
  feature03ShortTitle?: string | null;
  feature03Description?: string | null;
  feature03Image1?: (number | null) | Media;
  feature03Image2?: (number | null) | Media;
  feature03Image3?: (number | null) | Media;
  feature03Image4?: (number | null) | Media;
  feature03Image5?: (number | null) | Media;
  feature03Image6?: (number | null) | Media;
  feature04Title?: string | null;
  feature04ShortTitle?: string | null;
  feature04Description?: string | null;
  feature04Image1?: (number | null) | Media;
  feature04Image2?: (number | null) | Media;
  feature05Title?: string | null;
  feature05ShortTitle?: string | null;
  feature05Description?: string | null;
  feature05Image1?: (number | null) | Media;
  feature05Image2?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sphere-3d".
 */
export interface Sphere3D {
  id: number;
  status?: ('draft' | 'published') | null;
  enabled?: boolean | null;
  title?: string | null;
  /**
   * 3D模型文件地址
   */
  modelUrl?: string | null;
  backgroundColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simple-cta".
 */
export interface SimpleCta {
  id: number;
  status?: ('draft' | 'published') | null;
  title?: string | null;
  subtitle?: string | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  image1?: (number | null) | Media;
  image2?: (number | null) | Media;
  image3?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-products".
 */
export interface FeaturedProduct {
  id: number;
  status?: ('draft' | 'published') | null;
  title?: string | null;
  description?: string | null;
  viewAllButtonText?: string | null;
  /**
   * Select and order product series. API will automatically return 3 random products per series.
   */
  categories?: (number | ProductSery)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-advantages".
 */
export interface BrandAdvantage {
  id: number;
  status?: ('draft' | 'published') | null;
  image?: (number | null) | Media;
  advantage01Text?: string | null;
  /**
   * Lucide React 图标名称，例如: Sparkles, Target, Component
   */
  advantage01Icon?: string | null;
  advantage02Text?: string | null;
  /**
   * Lucide React 图标名称
   */
  advantage02Icon?: string | null;
  advantage03Text?: string | null;
  /**
   * Lucide React 图标名称
   */
  advantage03Icon?: string | null;
  advantage04Text?: string | null;
  /**
   * Lucide React 图标名称
   */
  advantage04Icon?: string | null;
  advantage05Text?: string | null;
  /**
   * Lucide React 图标名称
   */
  advantage05Icon?: string | null;
  advantage06Text?: string | null;
  /**
   * Lucide React 图标名称
   */
  advantage06Icon?: string | null;
  advantage07Text?: string | null;
  /**
   * Lucide React 图标名称
   */
  advantage07Icon?: string | null;
  advantage08Text?: string | null;
  /**
   * Lucide React 图标名称
   */
  advantage08Icon?: string | null;
  advantage09Text?: string | null;
  /**
   * Lucide React 图标名称
   */
  advantage09Icon?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oem-odm".
 */
export interface OemOdm {
  id: number;
  status?: ('draft' | 'published') | null;
  /**
   * 例如: "OEM"
   */
  oemTitle?: string | null;
  /**
   * OEM部分的背景图片
   */
  oemBgImage?: (number | null) | Media;
  /**
   * OEM部分的主图片
   */
  oemImage?: (number | null) | Media;
  /**
   * 例如: "At Busrom, we work closely with designers, retailers..."
   */
  oemDescription1?: string | null;
  /**
   * 例如: "Ready to turn your concept into a producible product?..."
   */
  oemDescription2?: string | null;
  /**
   * 例如: "ODM"
   */
  odmTitle?: string | null;
  /**
   * ODM部分的背景图片
   */
  odmBgImage?: (number | null) | Media;
  /**
   * ODM部分的主图片
   */
  odmImage?: (number | null) | Media;
  /**
   * 例如: "Fully Customized Structure & Size & Color"
   */
  odmDescription1?: string | null;
  /**
   * 例如: "Complete Solution - Just The Way You Want Them"
   */
  odmDescription2?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-steps".
 */
export interface QuoteStep {
  id: number;
  status?: ('draft' | 'published') | null;
  /**
   * 例如: "Design Project Solutions"
   */
  headerTitle?: string | null;
  /**
   * 例如: "Just Easy 5 Steps"
   */
  headerTitle2?: string | null;
  headerSubtitle?: string | null;
  headerDescription?: string | null;
  step01Text?: string | null;
  step01Image?: (number | null) | Media;
  step02Text?: string | null;
  step02Image?: (number | null) | Media;
  step03Text?: string | null;
  step03Image?: (number | null) | Media;
  step04Text?: string | null;
  step04Image?: (number | null) | Media;
  step05Text?: string | null;
  step05Image?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-form".
 */
export interface MainForm {
  id: number;
  status?: ('draft' | 'published') | null;
  /**
   * 选择要使用的表单配置。如果选择了，将使用 FormConfig 的字段配置；如果不选，则使用下方的占位符配置。
   */
  formConfig?: (number | null) | FormConfig;
  /**
   * 例如: "Premium Architectural Glass Hardware"
   */
  designTextLeft?: string | null;
  /**
   * 例如: "Customized Structure and Color"
   */
  designTextRight?: string | null;
  image1?: (number | null) | Media;
  image2?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-choose-busrom".
 */
export interface WhyChooseBusrom {
  id: number;
  status?: ('draft' | 'published') | null;
  title?: string | null;
  title2?: string | null;
  /**
   * 例如: "VIEW MORE INFORMATION"
   */
  viewMoreButtonText?: string | null;
  /**
   * 例如: "/about-us" 或 "https://example.com/about"
   */
  viewMoreButtonUrl?: string | null;
  reason01Title?: string | null;
  reason01Description?: string | null;
  /**
   * Lucide React 图标名称
   */
  reason01Icon?: string | null;
  reason01Image?: (number | null) | Media;
  reason02Title?: string | null;
  reason02Description?: string | null;
  /**
   * Lucide React 图标名称
   */
  reason02Icon?: string | null;
  reason02Image?: (number | null) | Media;
  reason03Title?: string | null;
  reason03Description?: string | null;
  /**
   * Lucide React 图标名称
   */
  reason03Icon?: string | null;
  reason03Image?: (number | null) | Media;
  reason04Title?: string | null;
  reason04Description?: string | null;
  /**
   * Lucide React 图标名称
   */
  reason04Icon?: string | null;
  reason04Image?: (number | null) | Media;
  reason05Title?: string | null;
  reason05Description?: string | null;
  /**
   * Lucide React 图标名称
   */
  reason05Icon?: string | null;
  reason05Image?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  status?: ('draft' | 'published') | null;
  title?: string | null;
  description?: string | null;
  /**
   * Select and order application categories (type=APPLICATION). API will automatically return 3 random case study items per category.
   */
  categories?: (number | Category)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-analysis".
 */
export interface BrandAnalysis {
  id: number;
  status?: ('draft' | 'published') | null;
  brandNameAnalysis?: {
    titlePart1?: string | null;
    titlePart2?: string | null;
    textPart1?: string | null;
    textPart2?: string | null;
  };
  brandCenter?: {
    title?: string | null;
    description?: string | null;
    largeImage?: (number | null) | Media;
    smallImage?: (number | null) | Media;
  };
  projectCenter?: {
    title?: string | null;
    description?: string | null;
    largeImage?: (number | null) | Media;
    smallImage?: (number | null) | Media;
  };
  serviceCenter?: {
    title?: string | null;
    description?: string | null;
    largeImage?: (number | null) | Media;
    smallImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-value".
 */
export interface BrandValue {
  id: number;
  status?: ('draft' | 'published') | null;
  title?: string | null;
  subtitle?: string | null;
  param1Title?: string | null;
  param1Description?: string | null;
  param1Image?: (number | null) | Media;
  param2Title?: string | null;
  param2Description?: string | null;
  param2Image?: (number | null) | Media;
  sloganTitle?: string | null;
  sloganDescription?: string | null;
  sloganImage?: (number | null) | Media;
  valueTitle?: string | null;
  valueDescription?: string | null;
  valueImage?: (number | null) | Media;
  visionTitle?: string | null;
  visionDescription?: string | null;
  visionImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Email service and notification settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-config".
 */
export interface EmailConfig {
  id: number;
  /**
   * SMTP server hostname (e.g., smtp.gmail.com)
   */
  smtpHost?: string | null;
  /**
   * Usually 587 (TLS) or 465 (SSL)
   */
  smtpPort?: string | null;
  smtpUser?: string | null;
  smtpPassword?: string | null;
  emailFromAddress?: string | null;
  emailFromName?: string | null;
  /**
   * Comma-separated list of emails to notify on form submissions
   */
  formNotificationEmails?: string | null;
  enableAutoReply?: boolean | null;
  autoReplySubject?: string | null;
  /**
   * Use {name} for submitter name
   */
  autoReplyTemplate?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure translation service for multi-language content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-config".
 */
export interface TranslationConfig {
  id: number;
  /**
   * Select the translation service to use
   */
  service: 'google' | 'deepl' | 'azure';
  /**
   * Enter your translation service API key
   */
  apiKey?: string | null;
  /**
   * Optional: Custom endpoint for self-hosted translation services
   */
  apiEndpoint?: string | null;
  /**
   * Default language to translate from
   */
  defaultSourceLang?: ('en' | 'zh' | 'auto') | null;
  /**
   * Limit translation requests to prevent API quota issues
   */
  maxRequestsPerMinute?: number | null;
  /**
   * Delay between translation requests
   */
  delayBetweenRequests?: number | null;
  /**
   * Enable or disable the translation feature
   */
  isEnabled?: boolean | null;
  lastTestedAt?: string | null;
  lastTestResult?: ('success' | 'failed' | 'not_tested') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        sectionType?: T;
        enabled?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  formConfig?: T;
  formTitle?: T;
  formPlaceholderName?: T;
  formPlaceholderEmail?: T;
  formPlaceholderMessage?: T;
  submitButtonText?: T;
  contactTitle?: T;
  contactEmailLabel?: T;
  contactEmail?: T;
  afterSalesLabel?: T;
  afterSalesEmail?: T;
  whatsappLabel?: T;
  whatsappNumber?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  workingHours?: T;
  officialNoticeTitle?: T;
  officialNoticeLine1?: T;
  officialNoticeLine2?: T;
  officialNoticeLine3?: T;
  officialNoticeLine4?: T;
  officialNoticeContent?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  column3Menus?: T;
  column4Menus?: T;
  copyrightText?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  logo?: T;
  favicon?: T;
  contactEmail?: T;
  contactPhone?: T;
  contactAddress?: T;
  googleMapsUrl?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  googleAnalyticsId?: T;
  googleTagManagerId?: T;
  facebook?: T;
  twitter?: T;
  instagram?: T;
  linkedin?: T;
  youtube?: T;
  tiktok?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-config_select".
 */
export interface ContactConfigSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  whatsapp?: T;
  wechat?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-config_select".
 */
export interface SocialConfigSelect<T extends boolean = true> {
  facebookUrl?: T;
  instagramUrl?: T;
  linkedinUrl?: T;
  youtubeUrl?: T;
  twitterUrl?: T;
  tiktokUrl?: T;
  pinterestUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-series-carousel_select".
 */
export interface ProductSeriesCarouselSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  items?: T;
  autoplay?: T;
  autoplaySpeed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-features_select".
 */
export interface ServiceFeaturesSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  subtitle?: T;
  feature01Title?: T;
  feature01ShortTitle?: T;
  feature01Description?: T;
  feature01Image1?: T;
  feature01Image2?: T;
  feature01Image3?: T;
  feature01Image4?: T;
  feature02Title?: T;
  feature02ShortTitle?: T;
  feature02Description?: T;
  feature02Image1?: T;
  feature02Image2?: T;
  feature03Title?: T;
  feature03ShortTitle?: T;
  feature03Description?: T;
  feature03Image1?: T;
  feature03Image2?: T;
  feature03Image3?: T;
  feature03Image4?: T;
  feature03Image5?: T;
  feature03Image6?: T;
  feature04Title?: T;
  feature04ShortTitle?: T;
  feature04Description?: T;
  feature04Image1?: T;
  feature04Image2?: T;
  feature05Title?: T;
  feature05ShortTitle?: T;
  feature05Description?: T;
  feature05Image1?: T;
  feature05Image2?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sphere-3d_select".
 */
export interface Sphere3DSelect<T extends boolean = true> {
  status?: T;
  enabled?: T;
  title?: T;
  modelUrl?: T;
  backgroundColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simple-cta_select".
 */
export interface SimpleCtaSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  subtitle?: T;
  ctaText?: T;
  ctaLink?: T;
  image1?: T;
  image2?: T;
  image3?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-products_select".
 */
export interface FeaturedProductsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  description?: T;
  viewAllButtonText?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-advantages_select".
 */
export interface BrandAdvantagesSelect<T extends boolean = true> {
  status?: T;
  image?: T;
  advantage01Text?: T;
  advantage01Icon?: T;
  advantage02Text?: T;
  advantage02Icon?: T;
  advantage03Text?: T;
  advantage03Icon?: T;
  advantage04Text?: T;
  advantage04Icon?: T;
  advantage05Text?: T;
  advantage05Icon?: T;
  advantage06Text?: T;
  advantage06Icon?: T;
  advantage07Text?: T;
  advantage07Icon?: T;
  advantage08Text?: T;
  advantage08Icon?: T;
  advantage09Text?: T;
  advantage09Icon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oem-odm_select".
 */
export interface OemOdmSelect<T extends boolean = true> {
  status?: T;
  oemTitle?: T;
  oemBgImage?: T;
  oemImage?: T;
  oemDescription1?: T;
  oemDescription2?: T;
  odmTitle?: T;
  odmBgImage?: T;
  odmImage?: T;
  odmDescription1?: T;
  odmDescription2?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-steps_select".
 */
export interface QuoteStepsSelect<T extends boolean = true> {
  status?: T;
  headerTitle?: T;
  headerTitle2?: T;
  headerSubtitle?: T;
  headerDescription?: T;
  step01Text?: T;
  step01Image?: T;
  step02Text?: T;
  step02Image?: T;
  step03Text?: T;
  step03Image?: T;
  step04Text?: T;
  step04Image?: T;
  step05Text?: T;
  step05Image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-form_select".
 */
export interface MainFormSelect<T extends boolean = true> {
  status?: T;
  formConfig?: T;
  designTextLeft?: T;
  designTextRight?: T;
  image1?: T;
  image2?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-choose-busrom_select".
 */
export interface WhyChooseBusromSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  title2?: T;
  viewMoreButtonText?: T;
  viewMoreButtonUrl?: T;
  reason01Title?: T;
  reason01Description?: T;
  reason01Icon?: T;
  reason01Image?: T;
  reason02Title?: T;
  reason02Description?: T;
  reason02Icon?: T;
  reason02Image?: T;
  reason03Title?: T;
  reason03Description?: T;
  reason03Icon?: T;
  reason03Image?: T;
  reason04Title?: T;
  reason04Description?: T;
  reason04Icon?: T;
  reason04Image?: T;
  reason05Title?: T;
  reason05Description?: T;
  reason05Icon?: T;
  reason05Image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  description?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-analysis_select".
 */
export interface BrandAnalysisSelect<T extends boolean = true> {
  status?: T;
  brandNameAnalysis?:
    | T
    | {
        titlePart1?: T;
        titlePart2?: T;
        textPart1?: T;
        textPart2?: T;
      };
  brandCenter?:
    | T
    | {
        title?: T;
        description?: T;
        largeImage?: T;
        smallImage?: T;
      };
  projectCenter?:
    | T
    | {
        title?: T;
        description?: T;
        largeImage?: T;
        smallImage?: T;
      };
  serviceCenter?:
    | T
    | {
        title?: T;
        description?: T;
        largeImage?: T;
        smallImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-value_select".
 */
export interface BrandValueSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  subtitle?: T;
  param1Title?: T;
  param1Description?: T;
  param1Image?: T;
  param2Title?: T;
  param2Description?: T;
  param2Image?: T;
  sloganTitle?: T;
  sloganDescription?: T;
  sloganImage?: T;
  valueTitle?: T;
  valueDescription?: T;
  valueImage?: T;
  visionTitle?: T;
  visionDescription?: T;
  visionImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-config_select".
 */
export interface EmailConfigSelect<T extends boolean = true> {
  smtpHost?: T;
  smtpPort?: T;
  smtpUser?: T;
  smtpPassword?: T;
  emailFromAddress?: T;
  emailFromName?: T;
  formNotificationEmails?: T;
  enableAutoReply?: T;
  autoReplySubject?: T;
  autoReplyTemplate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-config_select".
 */
export interface TranslationConfigSelect<T extends boolean = true> {
  service?: T;
  apiKey?: T;
  apiEndpoint?: T;
  defaultSourceLang?: T;
  maxRequestsPerMinute?: T;
  delayBetweenRequests?: T;
  isEnabled?: T;
  lastTestedAt?: T;
  lastTestResult?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnsBlock".
 */
export interface TwoColumnsBlock {
  leftColumn: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  rightColumn: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  columnRatio?: ('1:1' | '2:1' | '1:2' | '3:1' | '1:3') | null;
  gap?: ('small' | 'normal' | 'large') | null;
  verticalAlign?: ('top' | 'center' | 'bottom') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeColumnsBlock".
 */
export interface ThreeColumnsBlock {
  leftColumn: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  centerColumn: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  rightColumn: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  columnRatio?: ('1:1:1' | '2:1:1' | '1:2:1' | '1:1:2') | null;
  gap?: ('small' | 'normal' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SidebarBlock".
 */
export interface SidebarBlock {
  sidebarPosition?: ('left' | 'right') | null;
  mainContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sidebarContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sidebarWidth?: ('small' | 'medium' | 'large') | null;
  gap?: ('small' | 'normal' | 'large') | null;
  sidebarStyle?: ('default' | 'bordered' | 'background' | 'card') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sidebar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlock".
 */
export interface ContainerBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  maxWidth?: ('small' | 'medium' | 'large' | 'xlarge' | 'full') | null;
  padding?: ('none' | 'small' | 'normal' | 'large') | null;
  backgroundColor?: ('none' | 'light-gray' | 'white' | 'primary' | 'secondary') | null;
  border?: boolean | null;
  shadow?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'container';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}